/***************************************************************************\
 *                            🕸 KresMer 🕸
 *       "Kreslennya Merezh" - network diagram editor and viewer
 *      Copyright (C) 2022-2026 Dmitriy Stepanenko. All Rights Reserved.
 * -----------------------------------------------------------------------
 *              Browser extension service worker script
 ***************************************************************************/

import browser from 'webextension-polyfill';

const interceptionMarker = "in-brext";
const ourMimeTypes = ["application/x-kresmer-drawing", "image/kre+xml"];
const ourFileType = ".kre";

// Intercept opening files by their extension
browser.webNavigation.onBeforeNavigate.addListener(async (details) => {
    // Intercept the main frame only
    if (details.frameId !== 0) return;

    try {
        const url = new URL(details.url);
        if (url.searchParams.has(interceptionMarker)) return;

        if (url.pathname.endsWith(ourFileType)) {
            const viewerUrl = makeViewerURL(details.url);
            await browser.tabs.update(details.tabId, { url: viewerUrl });
        }//if
    } catch (error) {
        console.error('Error in webNavigation:', error);
    }
});


// Intercept opening files by their MIME-type
browser.webRequest.onHeadersReceived.addListener(
    (details) => {
        // Ignore requests generated by ourselves
        if (details.initiator?.includes('-extension://')) return;
        // also ignore requests fro the child frames
        if (details.frameId !== 0) return;

        const contentTypeHeader = details.responseHeaders?.find(
            (header) => header.name.toLowerCase() === 'content-type'
        );

        const mimeType = contentTypeHeader?.value?.split(';')[0].trim();

        if (mimeType && ourMimeTypes.includes(mimeType)) {
            const cleanHeaders = details.responseHeaders?.filter(
            (header) => header.name.toLowerCase() !== 'content-disposition'
            ) || [];

            const viewerUrl = makeViewerURL(details.url);
            const ruleId = 2; // Unique ID for our rule

            // Create a dynamic rule exactly for this request
            browser.declarativeNetRequest.updateDynamicRules({
                removeRuleIds: [ruleId],
                addRules: [
                    {
                        id: ruleId,
                        priority: 2, // higher priority than for the common rules
                        action: {
                            type: 'redirect',
                            redirect: { url: viewerUrl }
                        },
                        condition: {
                            urlFilter: details.url,
                            resourceTypes: ['main_frame']
                        }
                    }
                ]
            }).then(() => {
                // Reload the tab with the original URL to make browser apply the new rule
                browser.tabs.update(details.tabId, { url: details.url });
            });

            return { responseHeaders: cleanHeaders };
        }//if
    },
    { urls: ['<all_urls>'], types: ['main_frame'] }, // intercept only requests from the main frame
    ['responseHeaders']
);


// Prevent browser from downloading our file
(browser.downloads as any).onDeterminingFilename.addListener(
    (downloadItem: browser.Downloads.DownloadItem, suggest: () => void) => 
{
    // Make sure that the file is ours
    const shouldIntercept = 
        (downloadItem.url.endsWith(ourFileType) || (downloadItem.mime && ourMimeTypes.includes(downloadItem.mime))) &&
        downloadItem.state === "in_progress" && !downloadItem.url.startsWith("file://");
    if (shouldIntercept) {

        // Immediately cancel the download
        browser.downloads.cancel(downloadItem.id).then(() => {
            // Cleanup the history from the failed entry
            browser.downloads.erase({ id: downloadItem.id });
        });

        // Unblock the thread
        suggest();
        return;
    }//if

    // If the file is not ours, just let the download continue
    suggest();
});


function makeViewerURL(url: string) {
    return browser.runtime.getURL(`src/viewer.html?file=${encodeURIComponent(url)}&${interceptionMarker}`);
}//makeViewerURL

