/***************************************************************************\
 *                            🕸 KresMer 🕸
 *       "Kreslennya Merezh" - network diagram editor and viewer
 *      Copyright (C) 2022-2026 Dmitriy Stepanenko. All Rights Reserved.
 * -----------------------------------------------------------------------
 *              Browser extension service worker script
 ***************************************************************************/

import browser from 'webextension-polyfill';

// Intercept opening files by their extension
browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    if (changeInfo.url && changeInfo.url.endsWith('.kre') && !(new URL(changeInfo.url)).protocol.includes('-extension')) {
        // Stop the current tab from loading the .kre file directly by navigating to a blank page first
        browser.tabs.update(tabId, { url: 'about:blank' });

        // Open the viewer page with the .kre file URL as a query parameter
        const viewerUrl = makeViewerURL(changeInfo.url);
        browser.tabs.update(tabId, { url: viewerUrl });
    }
});

// Intercept opening files by their MIME-type
browser.webRequest.onHeadersReceived.addListener(
    (details) => {
        // Ignore requests generated by ourselves
        if (details.initiator?.includes('-extension://')) return;
        // also ignore requests fro the child frames
        if (details.frameId !== 0) return;

        const contentTypeHeader = details.responseHeaders?.find(
            (header) => header.name.toLowerCase() === 'content-type'
        );

        const mimeType = contentTypeHeader?.value?.split(';')[0].trim();

        if (mimeType === 'application/x-kresmer-drawing') {

            const viewerUrl = makeViewerURL(details.url);
            const ruleId = 2; // Unique ID for our rule

            // Create a dynamic rule exactly for this request
            browser.declarativeNetRequest.updateDynamicRules({
                removeRuleIds: [ruleId],
                addRules: [
                    {
                        id: ruleId,
                        priority: 2, // higher priority than for the common rules
                        action: {
                            type: 'redirect',
                            redirect: { url: viewerUrl.toString() }
                        },
                        condition: {
                            urlFilter: details.url,
                            resourceTypes: ['main_frame']
                        }
                    }
                ]
            }).then(() => {
                // Reload the tab with the original URL to make browser apply the new rule
                browser.tabs.update(details.tabId, { url: details.url });
            });
        }
    },
    { urls: ['<all_urls>'], types: ['main_frame'] }, // intercept only requests from the main frame
    ['responseHeaders']
);

function makeViewerURL(url: string) {
    return browser.runtime.getURL(`src/viewer.html?file=${encodeURIComponent(url)}&in-brext`);
}//makeViewerURL

