/***************************************************************************\
 *                            🕸 KresMer 🕸
 *       "Kreslennya Merezh" - network diagram editor and viewer
 *      Copyright (C) 2022-2026 Dmitriy Stepanenko. All Rights Reserved.
 * -----------------------------------------------------------------------
 *              Browser extension service worker script
 ***************************************************************************/

import browser from 'webextension-polyfill';

const interceptionMarker = "in-brext";
const ourMimeTypes = ["application/x-kresmer-drawing", "image/kre+xml"];
const ourFileType = ".kre";

// Intercept opening files by their extension
browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    if (changeInfo.url && changeInfo.url.endsWith(ourFileType) && !(new URL(changeInfo.url)).protocol.includes('-extension')) {
        // Stop the current tab from loading the .kre file directly by navigating to a blank page first
        browser.tabs.update(tabId, { url: 'about:blank' });

        // Open the viewer page with the .kre file URL as a query parameter
        const viewerUrl = makeViewerURL(changeInfo.url);
        browser.tabs.update(tabId, { url: viewerUrl });
    }
});

// Intercept opening files by their MIME-type
browser.webRequest.onHeadersReceived.addListener(
    (details) => {
        // Ignore requests generated by ourselves
        if (details.initiator?.includes('-extension://')) return;
        // also ignore requests fro the child frames
        if (details.frameId !== 0) return;

        const contentTypeHeader = details.responseHeaders?.find(
            (header) => header.name.toLowerCase() === 'content-type'
        );

        const mimeType = contentTypeHeader?.value?.split(';')[0].trim();

        if (mimeType && ourMimeTypes.includes(mimeType)) {
            const cleanHeaders = details.responseHeaders?.filter(
            (header) => header.name.toLowerCase() !== 'content-disposition'
            ) || [];

            const viewerUrl = makeViewerURL(details.url);
            const ruleId = 2; // Unique ID for our rule

            // Create a dynamic rule exactly for this request
            browser.declarativeNetRequest.updateDynamicRules({
                removeRuleIds: [ruleId],
                addRules: [
                    {
                        id: ruleId,
                        priority: 2, // higher priority than for the common rules
                        action: {
                            type: 'redirect',
                            redirect: { url: viewerUrl.toString() }
                        },
                        condition: {
                            urlFilter: details.url,
                            resourceTypes: ['main_frame']
                        }
                    }
                ]
            }).then(() => {
                // Reload the tab with the original URL to make browser apply the new rule
                browser.tabs.update(details.tabId, { url: details.url });
            });

            return { responseHeaders: cleanHeaders };
        }//if
    },
    { urls: ['<all_urls>'], types: ['main_frame'] }, // intercept only requests from the main frame
    ['responseHeaders']
);


(browser.downloads as any).onDeterminingFilename.addListener(
    (downloadItem: browser.Downloads.DownloadItem, suggest: () => void) => 
{
    // Check that file is ours
    if (downloadItem.url.endsWith(ourFileType) || (downloadItem.mime && ourMimeTypes.includes(downloadItem.mime))) {

        // Immediately cancel the download
        browser.downloads.cancel(downloadItem.id).then(() => {
            // Подчищаем историю, чтобы в списке загрузок не висел "сбой"
            browser.downloads.erase({ id: downloadItem.id });
        });

        // Unblock the process
        suggest();
        return;
    }//if

    // If the file is not ours, just let the download continue
    suggest();
});


function makeViewerURL(url: string) {
    return browser.runtime.getURL(`src/viewer.html?file=${encodeURIComponent(url)}&${interceptionMarker}`);
}//makeViewerURL

